services:
    db:
      image: postgres:16.3
      container_name: postgres-db
      environment:
        POSTGRES_DB: gradeflow
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      volumes: 
        - db-data:/var/lib/postgressql/data
      ports:
        - "5433:5432"
    
    redis:
      image: redis:6.2-alpine
      container_name: gradeflow-redis
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      command: ["redis-server", "--appendonly", "yes"]

volumes:
  db-data:
  redis_data:
