[project]
name = "python-service"
version = "0.1.0"
description = "Gabarito image processing microservice"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "numpy>=2.2.4",
    "opencv-python>=4.11.0.86",
    "pyright>=1.1.397",
]
